spring:
prot :8084
datasource:
url: jdbc:mysql://192.168.2.56:3306/myactiviti?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
username: root
password: 123456
driverClassName: com.mysql.jdbc.Driver
activiti:
check-process-definitions: false
security:
basic:
enabled: false
